@startuml
participant Actor
Actor -> main : main
activate main
main -> Ex2_1 : createTextFiles
activate Ex2_1
Ex2_1 --> main
deactivate Ex2_1
main -> Ex2_1 : getNumOfLines
activate Ex2_1
Ex2_1 --> main
deactivate Ex2_1
main -> Ex2_1 : getNumOfLinesThreads
activate Ex2_1
create LineCounterThread
Ex2_1 -> LineCounterThread : new
activate LineCounterThread
LineCounterThread --> Ex2_1
deactivate LineCounterThread
Ex2_1 --> main
deactivate Ex2_1
main -> Ex2_1 : getNumOfLinesThreadPool
activate Ex2_1
create LineCounterCallable
Ex2_1 -> LineCounterCallable : new
activate LineCounterCallable
LineCounterCallable --> Ex2_1
deactivate LineCounterCallable
Ex2_1 --> main
deactivate Ex2_1
main -> main : cleanFinder
activate main
main --> main
deactivate main
return
@enduml